version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
